import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


# ============================================================
# MODEL CONFIGURATION
# ============================================================

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

print("Loading MyanTone AI model...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    dtype=torch.float32,
)

device = "cpu"
model.to(device)

print("MyanTone AI model loaded successfully.")


# ============================================================
# MYANTONE TRANSLATION FUNCTION
# ============================================================

def translate_myanmar(
    text: str,
    tone: str = "professional",
    context: str = "general",
    audience: str = "auto",
):
    """
    Convert Myanmar text into natural English communication.

    Args:
        text: Myanmar message from the user.
        tone: Desired English tone.
        context: Communication context.
        audience: Intended audience.

    Returns:
        Natural English message generated by Qwen.
    """

    # --------------------------------------------------------
    # DEBUG INPUT
    # --------------------------------------------------------

    print("\n========== DEBUG INPUT ==========")
    print("repr(text):")
    print(repr(text))
    print("\ntext:")
    print(text)
    print("=================================\n")

    # --------------------------------------------------------
    # PROMPT
    # --------------------------------------------------------

    prompt = f"""
You are MyanTone AI, a Myanmar-to-English communication assistant.

Your task is to understand the meaning and intent of the Myanmar message
and rewrite it as ONE natural English communication message.

IMPORTANT RULES:

1. Understand the Myanmar meaning before generating English.
2. Preserve the original meaning and intent.
3. Do NOT translate word-for-word.
4. Do NOT invent information.
5. Do NOT change the situation.
6. Do NOT add explanations.
7. Do NOT describe the translation.
8. Do NOT mention that you are an AI.
9. Do NOT say the message is incomplete unless it is genuinely impossible
   to understand.
10. Return ONLY the final English message.
11. Do NOT use quotation marks.
12. Do NOT add labels such as:
    - Translation:
    - Natural English:
    - English:
    - Result:
13. Keep the response concise and natural.
14. Write as if the user is actually sending this message to another person.

Communication context: {context}
Audience: {audience}
Desired tone: {tone}

Myanmar message:
{text}

Final English message:
""".strip()

    # --------------------------------------------------------
    # CHAT TEMPLATE
    # --------------------------------------------------------

    messages = [
        {
            "role": "system",
            "content": (
                "You are MyanTone AI. "
                "You understand Myanmar messages and convert their meaning "
                "into natural English communication. "
                "Return only the final English message."
            ),
        },
        {
            "role": "user",
            "content": prompt,
        },
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    # --------------------------------------------------------
    # TOKENIZE
    # --------------------------------------------------------

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt",
    ).to(device)

    # --------------------------------------------------------
    # GENERATE
    # --------------------------------------------------------

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=80,
            do_sample=False,
        )

    # --------------------------------------------------------
    # REMOVE INPUT TOKENS
    # --------------------------------------------------------

    generated = outputs[0][inputs["input_ids"].shape[1]:]

    # --------------------------------------------------------
    # DECODE OUTPUT
    # --------------------------------------------------------

    result = tokenizer.decode(
        generated,
        skip_special_tokens=True,
    ).strip()

    return result


# ============================================================
# DIRECT TEST
# ============================================================

if __name__ == "__main__":

    test_text = "ဒီနေ့ meeting မတက်နိုင်ဘူးလို့ အလုပ်ကလူကို ပြောချင်တယ်။"

    result = translate_myanmar(
        test_text,
        tone="professional",
        context="workplace",
        audience="colleague",
    )

    # --------------------------------------------------------
    # FINAL RESULT
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("MYANTONE RESULT")
    print("=" * 60)
    print(result)
    print("=" * 60)
